CREATE TABLE users (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 username TEXT,
 phone TEXT,
 password TEXT,
 role TEXT DEFAULT 'user',
 created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE projects (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 title TEXT,
 description TEXT,
 image TEXT,
 url TEXT
);

CREATE TABLE study_notes (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 title TEXT,
 pdf_url TEXT
);

CREATE TABLE updates (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 title TEXT,
 content TEXT,
 created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
