CREATE TABLE users(
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 username TEXT UNIQUE,
 phone TEXT UNIQUE,
 password_hash TEXT,
 role TEXT DEFAULT 'user',
 banned INTEGER DEFAULT 0,
 created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE projects(
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 title TEXT,
 description TEXT,
 image TEXT,
 url TEXT,
 created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE study_notes(
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 title TEXT,
 pdf_url TEXT,
 created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE updates(
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 title TEXT,
 content TEXT,
 created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public_chat(
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 user TEXT,
 message TEXT,
 created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE analytics(
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 event TEXT,
 user_agent TEXT,
 timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);